# -*- coding: utf-8 -*-
"""Deeksha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ThDTe-Zh-KoJYlghlft-Wj6JnE7rXDDp
"""

print("hello python")

print(3*4)

print('"old is gold"- deeksha')

print("neha and praveen \nloves to read books and code \nthis is much fun!!")

name = 'deeksha'
age = 10 + 3
print(f'hi my name is {name} and i am {age} years old')

magic_number=5**4%333
magic_number

print("basket" + "ball")

first_name = "deeksha"
last_name = "sam"
print(first_name + "     " +last_name)



first_name = "deeksha"
last_name = " sam"
full_name = first_name + last_name
print(full_name)

full_name = first_name + " " + last_name
print(full_name)

print(100 * "deeksha!!")

my_favourite_desserts = ['cake',' ice cream']
print(my_favourite_desserts)

robot_answers = (True , False )
facts_about_deeksha = ('neha', 12 , True)

my_favourite_desserts[1]

sam = ['nose', 'eyes', 'mouth', 'ears', 'hands']
sam[2:4]

sam[:]

sam[:4]

sam[1:]

'cake' in my_favourite_desserts

sam.append('legs')
print(sam)

sam.remove('hands')
print(sam)

del sam[2]
print(sam)

x=int(input())
y=int(input())
5

if x==y:

  d=4
  #hit_snooze_button = True
  print("neha is tired so she hits the snooze button")
elif x>y:
  
  print("mad deeksha")
print("good sam")

def dividecookiesequally(cookies, kids):
  return cookies/kids
dividecookiesequally(10, 0)

my_favourite_things= ['chocolate', 'christmas', 'blue', 'dogs', ' coding']
print(f"these are deeksha's favourite things: {my_favourite_things}")

random_items = ['basket', 'ball', 'tennis','table','book','Npstation', 'foot','hawali', 'game','box']
print(f"{random_items[6]} {random_items[1]}")

print(f"{random_items[2]} {random_items[1]}")

numbers = [1,2,3,4,5]
for number in numbers:
  print(number + 2)

for i in range(4):
  print(i)

for i in range(21, 26):
  print(i)

for i in range(10, 20, 2):
  print(i)

numbers = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
i = 0 
while(i < len(numbers)):
  if (numbers[i] + 2 )< 20:
    print(numbers[i] + 2)
  i += 1

people = ['mario', 'peach', 'luigi','daisy','tod','jackie']
desserts = ['star pudding','peach pie','popsicles','honey cake','cookies', 'creme brulee']
i = 0
while (i < len(people)):
  print(i)
  print(f"hi! my name is {people[i]}.my favourite dessert is {desserts[i]}")
  i += 1

nacho_friends = ['athletic', 'not athletic','older', 'athletic','younger','athletic','not athletic','older','athletic','athletic','older']
hula_hoops_by_swings = 0
hula_hoops_by_basketball_court = 0
i = 0
while (i < len(nacho_friends[i])):
  if (nacho_friends[i]) in ('younger', 'athletic'):
    hula_hoops_by_swings += 1
  else:
    hula_hoops_by_basketball_court += 1
  i += 1
print(f"cats at hula hoops by swings: { hula_hoops_by_swings}") 
print(f"cats by hula hoop by basketball court: {hula_hoops_by_basketball_court}")

full_name = "deeksha"
letters = list(full_name)
print(letters)
number_of_a = 0 
number_of_e = 0
number_of_i = 0
number_of_o = 0
number_of_u = 0
for letter in letters :
  if letter == 'a':
    number_of_a += 1
  elif letter == 'e':
    number_of_e += 1
  elif letter == 'i':
    number_of_i +=1
  elif letter == 'o':
     number_of_o +=1 
  elif letter == 'u':
    number_of_u += 1
print(number_of_a , number_of_e , number_of_i , number_of_o, number_of_u)

