import turtle
pen = turtle.Turtle()
pen.hideturtle()

turtle_stamp = turtle.Turtle()
turtle_stamp.shape('turtle')
turtle_stamp.color('green')
turtle_stamp.penup()

turtle_stamp.left(90)
turtle_stamp.forward(100)
turtle_stamp.stamp()
turtle_stamp.left(90)
turtle_stamp.forward(100)
turtle_stamp.stamp()
turtle_stamp.left(90)
turtle_stamp.forward(100)
turtle_stamp.stamp()
turtle_stamp.left(90)
turtle_stamp.forward(100)
turtle_stamp.stamp()
